#!/bin/bash
. /etc/rssh-agent.conf
if [ "$1" == "-k" ]; then
    kill $SSH_AGENT_PID
    exit 0
fi

SOCKET="${HOME}/.ssh-agent-hack-${RANDOM}"

# If persistent or kill when the child process is over...
if [ $# -gt 1 ]; then
    socat UNIX-LISTEN:${SOCKET} TCP4:127.0.0.1:${RPORT} &
else
    socat UNIX-LISTEN:${SOCKET},fork,unlink-close=0 TCP4:127.0.0.1:${RPORT} &
fi

SSH_AGENT_PID=$!
SSH_AUTH_SOCK=${SOCKET}

# Launch command, or just set env.
if [ $# -gt 0 ]; then
    export SSH_AUTH_SOCK
    export SSH_AGENT_PID
    $@
else
    echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}; export SSH_AUTH_SOCK"
    echo "SSH_AGENT_PID=${SSH_AGENT_PID}; export SSH_AGENT_PID"
fi
