#!/bin/bash
if [ "$1" != '-bg' ]; then
    nohup $0 -bg >/dev/null 2>&1 </dev/null &
    exit
fi
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa
#SOCAT_DEFAULT_LISTEN_IP="127.0.0.1"
socat TCP4-LISTEN:222,fork UNIX-CLIENT:$SSH_AUTH_SOCK
