#!/bin/bash

start() {
    /usr/local/sbin/rssh-agentd
}

stop() {
    /usr/local/sbin/rssh-agentd -k
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    sleep 5 # give the system a few seconds for processes to terminate.
    start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
