#!/bin/bash
RPORT=222
if [ "$1" != '-bg' ]; then
    nohup $0 -bg >/dev/null 2>&1 </dev/null &
    exit
fi
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa
socat TCP4-LISTEN:${RPORT},fork UNIX-CLIENT:$SSH_AUTH_SOCK
